### ISSUE TITLE
i dont know what is wrong with issue.anyone kinly help me!Thanks

### ISSUE THREAD

**Issue by nhatnamnguyengtvthcm** [xavierlesa/channels-asgi-mqtt#10]
(venv) E:\NIC\Project\water vending machine\serverapp>chasgimqtt -H 169.254.193.90  -p 1883 --topic=some_topic:2 serverapp.asgi:channel_layer
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\NIC\Project\water vending machine\serverapp\venv\Scripts\chasgimqtt.exe\__main__.py", line 7, in <module>
  File "e:\nic\project\water vending machine\serverapp\venv\lib\site-packages\chasgimqtt\cli.py", line 97, in main
    server.run()
  File "e:\nic\project\water vending machine\serverapp\venv\lib\site-packages\chasgimqtt\server.py", line 190, in run
    functools.partial(self.stop_server, signame)
  File "C:\Program Files\Python36\lib\asyncio\events.py", line 499, in add_signal_handler
    raise NotImplementedError
NotImplementedError

**Comment by xavierlesa** [comment]
@nhatnamnguyengtvthcm I did not test this on windows, but i think your issue is related to `SIGTERM`. Feel free to send a PR.
